=== Thanos-Labs/naval-data/data/ships.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://naval-data.local/schemas/ship.schema.json",
  "title": "Aircraft Carrier",
  "type": "object",
  "additionalProperties": false,
  "$defs": {
    "nullableText": {
      "type": [
        "string",
        "null"
      ]
    },
    "nullableDate": {
      "type": ["string", "null"],
      "pattern": "^(\\d{4}|\\d{4}-\\d{2}-\\d{2})$"
    },
    "nullablePennantNumber": {
      "type": ["string", "null"],
      "pattern": "^(?:[A-Z]{1,5}-?\\d{1,3}|\\d{2,3})$"
    },
    "metricMeasurement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "m"
      ],
      "properties": {
        "m": {
          "type": ["number", "null"],
          "minimum": 0
        },
        "ft": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "speedMeasurement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "knots"
      ],
      "properties": {
        "knots": {
          "type": ["number", "null"],
          "minimum": 0
        },
        "km_h": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "displacementMeasurement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "tons"
      ],
      "properties": {
        "tons": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0
        },
        "tonnes": {
          "type": "number",
          "minimum": 0
        }
      }
    }
  },
  "required": [
    "name",
    "dbpedia_uri",
    "wikipedia_url",
    "wikipedia_title",
    "country",
    "subtype",
    "class",
    "configuration",
    "manufacturer",
    "date_commissioned",
    "date_decommissioned",
    "decommissioning_reason",
    "in_service",
    "displacement",
    "pennant_number",
    "length",
    "beam",
    "draught",
    "speed"
  ],
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "dbpedia_uri": {
      "type": "string",
      "format": "uri"
    },
    "wikipedia_url": {
      "type": "string",
      "format": "uri"
    },
    "wikipedia_title": {
      "type": "string",
      "minLength": 1
    },
    "country": {
      "type": "string",
      "minLength": 1
    },
    "subtype": {
      "enum": [
        "aircraft carrier",
        "nuclear aircraft carrier",
        "helicopter carrier",
        "escort carrier",
        "light aircraft carrier",
        "fleet carrier",
        "seaplane carrier",
        "amphibious assault ship",
        "landing helicopter dock",
        "aircraft cruiser"
      ]
    },
    "class": {
      "$ref": "#/$defs/nullableText"
    },
    "configuration": {
      "enum": [
        "CATOBAR",
        "STOBAR",
        "STOVL",
        "helicopter",
        "seaplane"
      ]
    },
    "manufacturer": {
      "type": "string",
      "minLength": 1
    },
    "date_commissioned": {
      "$ref": "#/$defs/nullableDate"
    },
    "date_decommissioned": {
      "$ref": "#/$defs/nullableDate"
    },
    "decommissioning_reason": {
      "type": ["string", "null"],
      "enum": [
        "scrapped",
        "scuttled",
        "sunk",
        "target",
        "museum",
        "transferred",
        "cancelled",
        "converted",
        "retired",
        null
      ]
    },
    "in_service": {
      "type": "boolean"
    },
    "displacement": {
      "$ref": "#/$defs/displacementMeasurement"
    },
    "pennant_number": {
      "$ref": "#/$defs/nullablePennantNumber"
    },
    "length": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "beam": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "height": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "draught": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "speed": {
      "$ref": "#/$defs/speedMeasurement"
    }
  }
}

=== Thanos-Labs/naval-data/data/ships/hms_ocean.json
{
  "name": "HMS Ocean (R68)",
  "dbpedia_uri": "http://dbpedia.org/resource/HMS_Ocean_(R68)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/HMS_Ocean_(R68)",
  "wikipedia_title": "HMS Ocean (R68)",
  "country": "United Kingdom",
  "subtype": "light aircraft carrier",
  "class": "Colossus-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Alexander Stephen & Sons",
  "date_commissioned": "1945-08-08",
  "date_decommissioned": "1960",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 13401.659,
    "tons": 13190.0
  },
  "pennant_number": "R68",
  "length": {
    "ft": 2066.929,
    "m": 630.0
  },
  "beam": {
    "ft": 262.467,
    "m": 80.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 59.055,
    "m": 18.0
  },
  "speed": {
    "km_h": 46.3,
    "knots": 25.0
  }
}

=== Thanos-Labs/naval-data/data/ships/js_hyuga.json
{
  "name": "JS Hyūga",
  "dbpedia_uri": "http://dbpedia.org/resource/JS_Hyūga",
  "wikipedia_url": "http://en.wikipedia.org/wiki/JS_Hyūga",
  "wikipedia_title": "JS Hyūga",
  "country": "Japan",
  "subtype": "helicopter carrier",
  "class": "Hyūga-class helicopter destroyer",
  "configuration": "helicopter",
  "manufacturer": "IHI, Yokohama",
  "date_commissioned": "2009-03-18",
  "date_decommissioned": null,
  "decommissioning_reason": null,
  "in_service": true,
  "displacement": {
    "tonnes": 14173.854,
    "tons": 13950.0
  },
  "pennant_number": "DDH-181",
  "length": {
    "ft": 646.325,
    "m": 197.0
  },
  "beam": {
    "ft": 108.268,
    "m": 33.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "m": null
  },
  "speed": {
    "km_h": 55.56,
    "knots": 30.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_saidor.json
{
  "name": "USS Saidor",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Saidor",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Saidor",
  "wikipedia_title": "USS Saidor",
  "country": "United States",
  "subtype": "escort carrier",
  "class": "Commencement Bay-class escort carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Todd Pacific Shipyards",
  "date_commissioned": "1945-09-04",
  "date_decommissioned": "1947-09-12",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 21740.356,
    "tons": 21397.0
  },
  "pennant_number": null,
  "length": {
    "ft": 1827.428,
    "m": 557.0
  },
  "beam": {
    "ft": 246.063,
    "m": 75.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 104.987,
    "m": 32.0
  },
  "speed": {
    "km_h": 35.188,
    "knots": 19.0
  }
}

=== Thanos-Labs/naval-data/data/ships/mv_empire_macmahon.json
{
  "name": "MV Empire MacMahon",
  "dbpedia_uri": "http://dbpedia.org/resource/MV_Empire_MacMahon",
  "wikipedia_url": "http://en.wikipedia.org/wiki/MV_Empire_MacMahon",
  "wikipedia_title": "MV Empire MacMahon",
  "country": "United Kingdom",
  "subtype": "aircraft carrier",
  "class": null,
  "configuration": "CATOBAR",
  "manufacturer": "Swan Hunter & Wigham Richardson, Wallsend",
  "date_commissioned": null,
  "date_decommissioned": null,
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tons": null
  },
  "pennant_number": null,
  "length": {
    "ft": 1519.029,
    "m": 463.0
  },
  "beam": {
    "ft": 200.131,
    "m": 61.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "m": null
  },
  "speed": {
    "km_h": 20.372,
    "knots": 11.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_thetis_bay.json
{
  "name": "USS Thetis Bay",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Thetis_Bay",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Thetis_Bay",
  "wikipedia_title": "USS Thetis Bay",
  "country": "United States",
  "subtype": "escort carrier",
  "class": "Casablanca-class escort carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Kaiser Shipyards",
  "date_commissioned": "1944-04-12",
  "date_decommissioned": "1964-03-01",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tons": null
  },
  "pennant_number": "LPH-6",
  "length": {
    "m": null
  },
  "beam": {
    "m": null
  },
  "height": {
    "m": null
  },
  "draught": {
    "m": null
  },
  "speed": {
    "knots": null
  }
}

=== Thanos-Labs/naval-data/data/ships/hms_ravager.json
{
  "name": "HMS Ravager (D70)",
  "dbpedia_uri": "http://dbpedia.org/resource/HMS_Ravager_(D70)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/HMS_Ravager_(D70)",
  "wikipedia_title": "HMS Ravager (D70)",
  "country": "United States",
  "subtype": "escort carrier",
  "class": "Bogue-class escort carrier (USA) *Attacker-class escort carrier (UK)",
  "configuration": "CATOBAR",
  "manufacturer": "Seattle-Tacoma Shipbuilding Corporation, Tacoma, Washington",
  "date_commissioned": "1943-04-25",
  "date_decommissioned": "1946-04-12",
  "decommissioning_reason": "transferred",
  "in_service": false,
  "displacement": {
    "tonnes": 792.517,
    "tons": 780.0
  },
  "pennant_number": "D70",
  "length": {
    "ft": 1525.591,
    "m": 465.0
  },
  "beam": {
    "ft": 226.378,
    "m": 69.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 78.74,
    "m": 24.0
  },
  "speed": {
    "km_h": 33.336,
    "knots": 18.0
  }
}

=== Thanos-Labs/naval-data/data/ships/hmas_canberra.json
{
  "name": "HMAS Canberra (L02)",
  "dbpedia_uri": "http://dbpedia.org/resource/HMAS_Canberra_(L02)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/HMAS_Canberra_(L02)",
  "wikipedia_title": "HMAS Canberra (L02)",
  "country": "Australia",
  "subtype": "helicopter carrier",
  "class": "Canberra-class landing helicopter dock",
  "configuration": "helicopter",
  "manufacturer": "Navantia, Ferrol, Spain & BAE Systems Australia, Williamstown Dockyard, Australia",
  "date_commissioned": "2014-11-28",
  "date_decommissioned": null,
  "decommissioning_reason": null,
  "in_service": true,
  "displacement": {
    "tonnes": 27941.29,
    "tons": 27500.0
  },
  "pennant_number": "L02",
  "length": {
    "ft": 757.283,
    "m": 230.82
  },
  "beam": {
    "ft": 104.987,
    "m": 32.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 23.228,
    "m": 7.08
  },
  "speed": {
    "km_h": 37.04,
    "knots": 20.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_leyte.json
{
  "name": "USS Leyte (CV-32)",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Leyte_(CV-32)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Leyte_(CV-32)",
  "wikipedia_title": "USS Leyte (CV-32)",
  "country": "United States",
  "subtype": "fleet carrier",
  "class": "Essex-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Newport News Shipbuilding",
  "date_commissioned": "1946-04-11",
  "date_decommissioned": "1959-05-15",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 27534.871,
    "tons": 27100.0
  },
  "pennant_number": null,
  "length": {
    "ft": 2913.386,
    "m": 888.0
  },
  "beam": {
    "ft": 305.118,
    "m": 93.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 91.864,
    "m": 28.0
  },
  "speed": {
    "km_h": 61.116,
    "knots": 33.0
  }
}
