=== Thanos-Labs/naval-data/data/ships.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://naval-data.local/schemas/ship.schema.json",
  "title": "Aircraft Carrier",
  "type": "object",
  "additionalProperties": false,
  "$defs": {
    "nullableText": {
      "type": [
        "string",
        "null"
      ]
    },
    "nullableDate": {
      "type": ["string", "null"],
      "pattern": "^(\\d{4}|\\d{4}-\\d{2}-\\d{2})$"
    },
    "nullablePennantNumber": {
      "type": ["string", "null"],
      "pattern": "^(?:[A-Z]{1,5}-?\\d{1,3}|\\d{2,3})$"
    },
    "metricMeasurement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "m"
      ],
      "properties": {
        "m": {
          "type": ["number", "null"],
          "minimum": 0
        },
        "ft": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "speedMeasurement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "knots"
      ],
      "properties": {
        "knots": {
          "type": ["number", "null"],
          "minimum": 0
        },
        "km_h": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "displacementMeasurement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "tons"
      ],
      "properties": {
        "tons": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0
        },
        "tonnes": {
          "type": "number",
          "minimum": 0
        }
      }
    }
  },
  "required": [
    "name",
    "dbpedia_uri",
    "wikipedia_url",
    "wikipedia_title",
    "country",
    "subtype",
    "class",
    "configuration",
    "manufacturer",
    "date_commissioned",
    "date_decommissioned",
    "decommissioning_reason",
    "in_service",
    "displacement",
    "pennant_number",
    "length",
    "beam",
    "draught",
    "speed"
  ],
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "dbpedia_uri": {
      "type": "string",
      "format": "uri"
    },
    "wikipedia_url": {
      "type": "string",
      "format": "uri"
    },
    "wikipedia_title": {
      "type": "string",
      "minLength": 1
    },
    "country": {
      "type": "string",
      "minLength": 1
    },
    "subtype": {
      "enum": [
        "aircraft carrier",
        "nuclear aircraft carrier",
        "helicopter carrier",
        "escort carrier",
        "light aircraft carrier",
        "fleet carrier",
        "seaplane carrier",
        "amphibious assault ship",
        "landing helicopter dock",
        "aircraft cruiser"
      ]
    },
    "class": {
      "$ref": "#/$defs/nullableText"
    },
    "configuration": {
      "enum": [
        "CATOBAR",
        "STOBAR",
        "STOVL",
        "helicopter",
        "seaplane"
      ]
    },
    "manufacturer": {
      "type": "string",
      "minLength": 1
    },
    "date_commissioned": {
      "$ref": "#/$defs/nullableDate"
    },
    "date_decommissioned": {
      "$ref": "#/$defs/nullableDate"
    },
    "decommissioning_reason": {
      "type": ["string", "null"],
      "enum": [
        "scrapped",
        "scuttled",
        "sunk",
        "target",
        "museum",
        "transferred",
        "cancelled",
        "converted",
        "retired",
        null
      ]
    },
    "in_service": {
      "type": "boolean"
    },
    "displacement": {
      "$ref": "#/$defs/displacementMeasurement"
    },
    "pennant_number": {
      "$ref": "#/$defs/nullablePennantNumber"
    },
    "length": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "beam": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "height": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "draught": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "speed": {
      "$ref": "#/$defs/speedMeasurement"
    }
  }
}

=== Thanos-Labs/naval-data/data/ships/la_fayette.json
{
  "name": "French aircraft carrier La Fayette",
  "dbpedia_uri": "http://dbpedia.org/resource/French_aircraft_carrier_La_Fayette",
  "wikipedia_url": "http://en.wikipedia.org/wiki/French_aircraft_carrier_La_Fayette",
  "wikipedia_title": "French aircraft carrier La Fayette",
  "country": "France",
  "subtype": "light aircraft carrier",
  "class": "Independence-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "New York Shipbuilding Corporation",
  "date_commissioned": null,
  "date_decommissioned": null,
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 11176.516,
    "tons": 11000.0
  },
  "pennant_number": "R96",
  "length": {
    "ft": 2042.323,
    "m": 622.5
  },
  "beam": {
    "ft": 234.58,
    "m": 71.5
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 85.302,
    "m": 26.0
  },
  "speed": {
    "km_h": 57.412,
    "knots": 31.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_philippine_sea.json
{
  "name": "USS Philippine Sea (CV-47)",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Philippine_Sea_(CV-47)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Philippine_Sea_(CV-47)",
  "wikipedia_title": "USS Philippine Sea (CV-47)",
  "country": "United States",
  "subtype": "fleet carrier",
  "class": "Essex-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Fore River Shipyard",
  "date_commissioned": "1946-05-11",
  "date_decommissioned": "1958-12-28",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 27534.871,
    "tons": 27100.0
  },
  "pennant_number": null,
  "length": {
    "ft": 2913.386,
    "m": 888.0
  },
  "beam": {
    "ft": 305.118,
    "m": 93.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 91.864,
    "m": 28.0
  },
  "speed": {
    "km_h": 61.116,
    "knots": 33.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_badoeng_strait.json
{
  "name": "USS Badoeng Strait",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Badoeng_Strait",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Badoeng_Strait",
  "wikipedia_title": "USS Badoeng Strait",
  "country": "United States",
  "subtype": "escort carrier",
  "class": "Commencement Bay-class escort carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Todd-Pacific Shipyards",
  "date_commissioned": "1945-11-14",
  "date_decommissioned": "1957-05-17",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 21740.356,
    "tons": 21397.0
  },
  "pennant_number": null,
  "length": {
    "ft": 1827.428,
    "m": 557.0
  },
  "beam": {
    "ft": 246.063,
    "m": 75.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 104.987,
    "m": 32.0
  },
  "speed": {
    "km_h": 35.188,
    "knots": 19.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_bon_homme_richard.json
{
  "name": "USS Bon Homme Richard (CV-31)",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Bon_Homme_Richard_(CV-31)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Bon_Homme_Richard_(CV-31)",
  "wikipedia_title": "USS Bon Homme Richard (CV-31)",
  "country": "United States",
  "subtype": "fleet carrier",
  "class": "Essex-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "New York Naval Shipyard",
  "date_commissioned": "1944-11-26",
  "date_decommissioned": "1971-07-02",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 275.349,
    "tons": 271.0
  },
  "pennant_number": null,
  "length": {
    "ft": 2690.289,
    "m": 820.0
  },
  "beam": {
    "ft": 305.118,
    "m": 93.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 111.549,
    "m": 34.0
  },
  "speed": {
    "km_h": 61.116,
    "knots": 33.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_tarawa.json
{
  "name": "USS Tarawa (LHA-1)",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Tarawa_(LHA-1)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Tarawa_(LHA-1)",
  "wikipedia_title": "USS Tarawa (LHA-1)",
  "country": "United States",
  "subtype": "amphibious assault ship",
  "class": "Tarawa-class amphibious assault ship",
  "configuration": "STOVL",
  "manufacturer": "Ingalls Shipbuilding",
  "date_commissioned": "1976-05-29",
  "date_decommissioned": "2009-03-31",
  "decommissioning_reason": "sunk",
  "in_service": false,
  "displacement": {
    "tonnes": 39524.225,
    "tons": 38900.0
  },
  "pennant_number": "LHA-1",
  "length": {
    "ft": 2690.289,
    "m": 820.0
  },
  "beam": {
    "ft": 347.769,
    "m": 106.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 85.302,
    "m": 26.0
  },
  "speed": {
    "km_h": 44.448,
    "knots": 24.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_vella_gulf.json
{
  "name": "USS Vella Gulf (CVE-111)",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Vella_Gulf_(CVE-111)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Vella_Gulf_(CVE-111)",
  "wikipedia_title": "USS Vella Gulf (CVE-111)",
  "country": "United States",
  "subtype": "escort carrier",
  "class": "Commencement Bay-class escort carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Todd Pacific Shipyards",
  "date_commissioned": "1945-04-09",
  "date_decommissioned": "1946-08-09",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 21740.356,
    "tons": 21397.0
  },
  "pennant_number": "CVE-111",
  "length": {
    "ft": 1827.428,
    "m": 557.0
  },
  "beam": {
    "ft": 246.063,
    "m": 75.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 104.987,
    "m": 32.0
  },
  "speed": {
    "km_h": 35.188,
    "knots": 19.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_abraham_lincoln.json
{
  "name": "USS Abraham Lincoln (CVN-72)",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Abraham_Lincoln_(CVN-72)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Abraham_Lincoln_(CVN-72)",
  "wikipedia_title": "USS Abraham Lincoln (CVN-72)",
  "country": "United States",
  "subtype": "nuclear aircraft carrier",
  "class": "Nimitz-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Newport News Shipbuilding",
  "date_commissioned": "1989-11-11",
  "date_decommissioned": null,
  "decommissioning_reason": null,
  "in_service": true,
  "displacement": {
    "tonnes": 105.669,
    "tons": 104.0
  },
  "pennant_number": "CVN-72",
  "length": {
    "ft": 3582.677,
    "m": 1092.0
  },
  "beam": {
    "ft": 826.772,
    "m": 252.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 121.391,
    "m": 37.0
  },
  "speed": {
    "km_h": 55.56,
    "knots": 30.0
  }
}

=== Thanos-Labs/naval-data/data/ships/hms_ark_royal.json
{
  "name": "HMS Ark Royal (R09)",
  "dbpedia_uri": "http://dbpedia.org/resource/HMS_Ark_Royal_(R09)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/HMS_Ark_Royal_(R09)",
  "wikipedia_title": "HMS Ark Royal (R09)",
  "country": "United Kingdom",
  "subtype": "fleet carrier",
  "class": "Audacious-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Cammell Laird, Birkenhead, England",
  "date_commissioned": "1955-02-22",
  "date_decommissioned": "1979-02-14",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 37390.526,
    "tons": 36800.0
  },
  "pennant_number": "R09",
  "length": {
    "ft": 2637.795,
    "m": 804.0
  },
  "beam": {
    "ft": 367.454,
    "m": 112.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 32.808,
    "m": 10.0
  },
  "speed": {
    "km_h": 58.338,
    "knots": 31.5
  }
}
