=== Thanos-Labs/naval-data/data/ships.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://naval-data.local/schemas/ship.schema.json",
  "title": "Aircraft Carrier",
  "type": "object",
  "additionalProperties": false,
  "$defs": {
    "nullableText": {
      "type": [
        "string",
        "null"
      ]
    },
    "nullableDate": {
      "type": ["string", "null"],
      "pattern": "^(\\d{4}|\\d{4}-\\d{2}-\\d{2})$"
    },
    "nullablePennantNumber": {
      "type": ["string", "null"],
      "pattern": "^(?:[A-Z]{1,5}-?\\d{1,3}|\\d{2,3})$"
    },
    "metricMeasurement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "m"
      ],
      "properties": {
        "m": {
          "type": ["number", "null"],
          "minimum": 0
        },
        "ft": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "speedMeasurement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "knots"
      ],
      "properties": {
        "knots": {
          "type": ["number", "null"],
          "minimum": 0
        },
        "km_h": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "displacementMeasurement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "tons"
      ],
      "properties": {
        "tons": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0
        },
        "tonnes": {
          "type": "number",
          "minimum": 0
        }
      }
    }
  },
  "required": [
    "name",
    "dbpedia_uri",
    "wikipedia_url",
    "wikipedia_title",
    "country",
    "subtype",
    "class",
    "configuration",
    "manufacturer",
    "date_commissioned",
    "date_decommissioned",
    "decommissioning_reason",
    "in_service",
    "displacement",
    "pennant_number",
    "length",
    "beam",
    "draught",
    "speed"
  ],
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "dbpedia_uri": {
      "type": "string",
      "format": "uri"
    },
    "wikipedia_url": {
      "type": "string",
      "format": "uri"
    },
    "wikipedia_title": {
      "type": "string",
      "minLength": 1
    },
    "country": {
      "type": "string",
      "minLength": 1
    },
    "subtype": {
      "enum": [
        "aircraft carrier",
        "nuclear aircraft carrier",
        "helicopter carrier",
        "escort carrier",
        "light aircraft carrier",
        "fleet carrier",
        "seaplane carrier",
        "amphibious assault ship",
        "landing helicopter dock",
        "aircraft cruiser"
      ]
    },
    "class": {
      "$ref": "#/$defs/nullableText"
    },
    "configuration": {
      "enum": [
        "CATOBAR",
        "STOBAR",
        "STOVL",
        "helicopter",
        "seaplane"
      ]
    },
    "manufacturer": {
      "type": "string",
      "minLength": 1
    },
    "date_commissioned": {
      "$ref": "#/$defs/nullableDate"
    },
    "date_decommissioned": {
      "$ref": "#/$defs/nullableDate"
    },
    "decommissioning_reason": {
      "type": ["string", "null"],
      "enum": [
        "scrapped",
        "scuttled",
        "sunk",
        "target",
        "museum",
        "transferred",
        "cancelled",
        "converted",
        "retired",
        null
      ]
    },
    "in_service": {
      "type": "boolean"
    },
    "displacement": {
      "$ref": "#/$defs/displacementMeasurement"
    },
    "pennant_number": {
      "$ref": "#/$defs/nullablePennantNumber"
    },
    "length": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "beam": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "height": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "draught": {
      "$ref": "#/$defs/metricMeasurement"
    },
    "speed": {
      "$ref": "#/$defs/speedMeasurement"
    }
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_doris_miller.json
{
  "name": "USS Doris Miller",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Doris_Miller",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Doris_Miller",
  "wikipedia_title": "USS Doris Miller",
  "country": "United States",
  "subtype": "nuclear aircraft carrier",
  "class": "Gerald R. Ford-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Newport News Shipbuilding",
  "date_commissioned": "2034",
  "date_decommissioned": null,
  "decommissioning_reason": null,
  "in_service": false,
  "displacement": {
    "tons": null
  },
  "pennant_number": "CVN-81",
  "length": {
    "ft": 3628.609,
    "m": 1106.0
  },
  "beam": {
    "ft": 439.633,
    "m": 134.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 127.953,
    "m": 39.0
  },
  "speed": {
    "km_h": 55.56,
    "knots": 30.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_franklin_d_roosevelt.json
{
  "name": "USS Franklin D. Roosevelt",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Franklin_D._Roosevelt",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Franklin_D._Roosevelt",
  "wikipedia_title": "USS Franklin D. Roosevelt",
  "country": "United States",
  "subtype": "aircraft carrier",
  "class": "Midway-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "New York Naval Shipyard",
  "date_commissioned": "1945-10-27",
  "date_decommissioned": "1977-09-30",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 45722.111,
    "tons": 45000.0
  },
  "pennant_number": null,
  "length": {
    "ft": 3175.853,
    "m": 968.0
  },
  "beam": {
    "ft": 370.735,
    "m": 113.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 114.829,
    "m": 35.0
  },
  "speed": {
    "km_h": 61.116,
    "knots": 33.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_langley.json
{
  "name": "USS Langley (CVL-27)",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Langley_(CVL-27)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Langley_(CVL-27)",
  "wikipedia_title": "USS Langley (CVL-27)",
  "country": "France",
  "subtype": "light aircraft carrier",
  "class": "Independence-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "New York Shipbuilding Corporation",
  "date_commissioned": "1951-06-02",
  "date_decommissioned": "1963-03-20",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 11176.516,
    "tons": 11000.0
  },
  "pennant_number": "CVL-27",
  "length": {
    "ft": 2042.323,
    "m": 622.5
  },
  "beam": {
    "ft": 234.58,
    "m": 71.5
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 85.302,
    "m": 26.0
  },
  "speed": {
    "km_h": 57.412,
    "knots": 31.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_tripoli.json
{
  "name": "USS Tripoli (LPH-10)",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Tripoli_(LPH-10)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Tripoli_(LPH-10)",
  "wikipedia_title": "USS Tripoli (LPH-10)",
  "country": "United States",
  "subtype": "aircraft carrier",
  "class": "Iwo Jima-class amphibious assault ship",
  "configuration": "STOVL",
  "manufacturer": "Ingalls Shipbuilding",
  "date_commissioned": "1966-08-06",
  "date_decommissioned": "1995-09-15",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 19611.737,
    "tons": 19302.0
  },
  "pennant_number": "LPH-10",
  "length": {
    "ft": 1961.942,
    "m": 598.0
  },
  "beam": {
    "ft": 275.591,
    "m": 84.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 98.425,
    "m": 30.0
  },
  "speed": {
    "km_h": 42.596,
    "knots": 23.0
  }
}

=== Thanos-Labs/naval-data/data/ships/hms_triumph.json
{
  "name": "HMS Triumph (R16)",
  "dbpedia_uri": "http://dbpedia.org/resource/HMS_Triumph_(R16)",
  "wikipedia_url": "http://en.wikipedia.org/wiki/HMS_Triumph_(R16)",
  "wikipedia_title": "HMS Triumph (R16)",
  "country": "United Kingdom",
  "subtype": "light aircraft carrier",
  "class": "Colossus-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Hawthorn Leslie and Company",
  "date_commissioned": "1946-05-06",
  "date_decommissioned": "1981",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tonnes": 13564.226,
    "tons": 13350.0
  },
  "pennant_number": "R16",
  "length": {
    "ft": 2280.184,
    "m": 695.0
  },
  "beam": {
    "ft": 262.467,
    "m": 80.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 77.1,
    "m": 23.5
  },
  "speed": {
    "km_h": 46.3,
    "knots": 25.0
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_casablanca.json
{
  "name": "USS Casablanca",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Casablanca",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Casablanca",
  "wikipedia_title": "USS Casablanca",
  "country": "United States",
  "subtype": "escort carrier",
  "class": "Casablanca-class escort carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Kaiser Shipbuilding Company, Vancouver, Washington",
  "date_commissioned": "1943-07-08",
  "date_decommissioned": "1946-06-10",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tons": null
  },
  "pennant_number": "AVG-55",
  "length": {
    "m": null
  },
  "beam": {
    "m": null
  },
  "height": {
    "m": null
  },
  "draught": {
    "m": null
  },
  "speed": {
    "knots": null
  }
}

=== Thanos-Labs/naval-data/data/ships/uss_hollandia.json
{
  "name": "USS Hollandia",
  "dbpedia_uri": "http://dbpedia.org/resource/USS_Hollandia",
  "wikipedia_url": "http://en.wikipedia.org/wiki/USS_Hollandia",
  "wikipedia_title": "USS Hollandia",
  "country": "United States",
  "subtype": "escort carrier",
  "class": "Casablanca-class escort carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Kaiser Shipyards",
  "date_commissioned": "1944-06-01",
  "date_decommissioned": "1947-01-17",
  "decommissioning_reason": "scrapped",
  "in_service": false,
  "displacement": {
    "tons": null
  },
  "pennant_number": "CVE-97",
  "length": {
    "m": null
  },
  "beam": {
    "m": null
  },
  "height": {
    "m": null
  },
  "draught": {
    "m": null
  },
  "speed": {
    "knots": null
  }
}

=== Thanos-Labs/naval-data/data/ships/shoho.json
{
  "name": "Japanese aircraft carrier Shōhō",
  "dbpedia_uri": "http://dbpedia.org/resource/Japanese_aircraft_carrier_Shōhō",
  "wikipedia_url": "http://en.wikipedia.org/wiki/Japanese_aircraft_carrier_Shōhō",
  "wikipedia_title": "Japanese aircraft carrier Shōhō",
  "country": "Japan",
  "subtype": "aircraft carrier",
  "class": "Zuihō-class aircraft carrier",
  "configuration": "CATOBAR",
  "manufacturer": "Yokosuka Naval Arsenal",
  "date_commissioned": "1941-11-30",
  "date_decommissioned": null,
  "decommissioning_reason": "sunk",
  "in_service": false,
  "displacement": {
    "tonnes": 113.797,
    "tons": 112.0
  },
  "pennant_number": null,
  "length": {
    "ft": 2211.286,
    "m": 674.0
  },
  "beam": {
    "ft": 193.57,
    "m": 59.0
  },
  "height": {
    "m": null
  },
  "draught": {
    "ft": 68.898,
    "m": 21.0
  },
  "speed": {
    "km_h": 51.856,
    "knots": 28.0
  }
}
